##-----------------------------------------------------------------------------
##  Copyright (C) Fraunhofer MEVIS 2014  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------
##
## Project: IDEA
##    File: \n4\pkg\MrServers\MrVista\Ice\IceApplicationFunctors\IceDataExport\makefile.trs
## Version: 
##  Author: David Porter
##    Date:
##
##    Lang: make
##
## Descrip: Makefile fuer Target IceTemplate
##
##-----------------------------------------------------------------------------

##-----------------------------------------------------------------------------
## Naehere Informationen zum den moeglichen Macros im Makefile siehe
## MedMake-Dokumentation Q:/csw/MedMake/html/contents_t6.html
##

##-----------------------------------------------------------------------------
## enter NLS library
##

##-----------------------------------------------------------------------------
## enter local compiler flags
##

##-----------------------------------------------------------------------------
## enter local compiler paths
##
CPPFLAGS ( -DICEIDEAFUNCTORS_EXPORTS         )
CPPFLAGS ( -DBUILD_IceScanFunctors           )
CPPFLAGS ( -DBUILD_IceImageReconFunctors     )
CPPFLAGS ( -DNAMESPACE_ICE=IceFramework      )
CPPFLAGS ( -DPROJECT_NAMESPACE=NAMESPACE_DATA_EXPORT )
MSDEV_i586_WinNT400(CCCFLAGS(-Zm400))

##-----------------------------------------------------------------------------
## enter source files
##

## IceScanFunctors

CPPSOURCES ( DataExportFunctor )

## IceImageReconFunctors

## Configurator

CPPSOURCES ( DataExportConfigurator )

## Object map

CPPSOURCES ( DataExportObjectMap )

##-----------------------------------------------------------------------------
## enter local linker flags
##

##-----------------------------------------------------------------------------
## enter link libraries
##

LDLIBS(IceAlgos)
LDLIBS(IceBasic)
LDLIBS(IceUtils)
LDLIBS(MrParc)
LDLIBS(UTrace)
LDLIBS(IceImageReconFunctors)
#LDLIBS(IceScanFunctors) ERROR - WHY?

# StdExcept
MSDEV_i586_WinNT400(LDLIBS(MrClassDump))

# SEQData
MSDEV_WinNT400(LDLIBS(libMES4BV))
GCC_AMD_XLinux(LDLIBS(libMES))
GCC_Linux(LDLIBS(libMES))

# ace
MSDEV_WinNT400(LDLIBS(ace))
GCC_AMD_XLinux(LDLIBS(ace)) 
GCC_Linux(LDLIBS(ace)) 

##-----------------------------------------------------------------------------
## enter target name
##
LIB(IceDataExport)
EVPTLB(IceDataExport)

##-----------------------------------------------------------------------------
##  Copyright (C) Fraunhofer MEVIS 2014  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------

